### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by aremu-smog** [netlify/classnames-template-literals#5]
Any ideas on how I can enable Tailwind Intellisense for the plugin so that I get suggestions for classnames?

**Comment by Takazudo** [comment]
This issue will help you

https://github.com/ben-rogerson/twin.macro/discussions/227

**Comment by Takazudo** [comment]
```
  "tailwindCSS.experimental.classRegex": [
      "ctl\\(`([^`]*)"
  ],
```

<img width="1489" alt="ss 2021-06-15 15 49 03" src="https://user-images.githubusercontent.com/128233/122006026-4a29d500-cdf1-11eb-90af-7f4c444596c1.png">

**Comment by aremu-smog** [comment]
Checking this out now. Thanks a lot

**Comment by Takazudo** [comment]
👍👍
